apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.120.1
  labels:
    cnrm.cloud.google.com/component: cnrm-resource-stats-recorder
    cnrm.cloud.google.com/system: "true"
  name: cnrm-resource-stats-recorder
  namespace: cnrm-system
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      cnrm.cloud.google.com/component: cnrm-resource-stats-recorder
      cnrm.cloud.google.com/system: "true"
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cnrm.cloud.google.com/version: 1.120.1
      labels:
        cnrm.cloud.google.com/component: cnrm-resource-stats-recorder
        cnrm.cloud.google.com/system: "true"
    spec:
      containers:
      - args:
        - --prometheus-scrape-endpoint=:48797
        - --metric-interval=60
        command:
        - /configconnector/recorder
        env:
        - name: CONFIG_CONNECTOR_VERSION
          value: 1.120.1
        image: gcr.io/cnrm-eap/recorder:95ba956
        imagePullPolicy: Always
        name: recorder
        ports:
        - containerPort: 48797
          protocol: TCP
        - containerPort: 23232
        readinessProbe:
          httpGet:
            path: /ready
            port: 23232
          initialDelaySeconds: 7
          periodSeconds: 3
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 20m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
      enableServiceLinks: false
      hostNetwork: false
      serviceAccountName: cnrm-resource-stats-recorder
      terminationGracePeriodSeconds: 10
