---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: config-connector
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v1.120.1
  url: https://github.com/GoogleCloudPlatform/k8s-config-connector.git
