---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-2
  name: nginx-2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-2
    spec:
      containers:
      - image: nginx
        name: nginx-2
        resources: {}
status: {}
